/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwarajRouteImport } from './routes/swaraj'
import { Route as FarmMachineryRouteImport } from './routes/farm-machinery'
import { Route as IndexRouteImport } from './routes/index'

const SwarajRoute = SwarajRouteImport.update({
  id: '/swaraj',
  path: '/swaraj',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmMachineryRoute = FarmMachineryRouteImport.update({
  id: '/farm-machinery',
  path: '/farm-machinery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farm-machinery': typeof FarmMachineryRoute
  '/swaraj': typeof SwarajRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farm-machinery': typeof FarmMachineryRoute
  '/swaraj': typeof SwarajRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farm-machinery': typeof FarmMachineryRoute
  '/swaraj': typeof SwarajRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/farm-machinery' | '/swaraj'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/farm-machinery' | '/swaraj'
  id: '__root__' | '/' | '/farm-machinery' | '/swaraj'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmMachineryRoute: typeof FarmMachineryRoute
  SwarajRoute: typeof SwarajRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swaraj': {
      id: '/swaraj'
      path: '/swaraj'
      fullPath: '/swaraj'
      preLoaderRoute: typeof SwarajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-machinery': {
      id: '/farm-machinery'
      path: '/farm-machinery'
      fullPath: '/farm-machinery'
      preLoaderRoute: typeof FarmMachineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmMachineryRoute: FarmMachineryRoute,
  SwarajRoute: SwarajRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
